<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\PVALogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Connect.png" />
    <None Remove="Images\Copy.png" />
    <None Remove="Images\Cut.png" />
    <None Remove="Images\Disconnect.png" />
    <None Remove="Images\Load.png" />
    <None Remove="Images\Paste.png" />
    <None Remove="Images\PVALogo.png" />
    <None Remove="Images\Save.png" />
    <None Remove="Images\Settings.png" />
	<AdditionalFiles Include="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Connecting.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Connected.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Copy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Cut.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Disconnect.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Load.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Paste.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\PVALogo.ico" />
    <Content Include="Images\PVALogo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Save.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\Settings.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Unity" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Themes.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
